"""add_table_code

Revision ID: 5629ea2f4735
Revises: 226eb7b4780f
Create Date: 2026-01-04 16:27:59.926700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5629ea2f4735'
down_revision: Union[str, None] = '226eb7b4780f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_column('rooms', 'code')
    # ### end Alembic commands ###
