"""Add student_attempts table

Revision ID: e22356a186b8
Revises: 5629ea2f4735
Create Date: 2026-01-05 19:25:58.458535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e22356a186b8'
down_revision: Union[str, None] = '5629ea2f4735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', name='attemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_student_attempts_assessment_id'), 'student_attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_student_attempts_student_id'), 'student_attempts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_attempts_student_id'), table_name='student_attempts')
    op.drop_index(op.f('ix_student_attempts_assessment_id'), table_name='student_attempts')
    op.drop_table('student_attempts')
    # ### end Alembic commands ###
